language: node_js
node_js: node
cache:
  directories:
    - node_modules
    - client/node_modules
before_install:
  - cd client
  - npm install
  - npm run build
  - cd ../
script: 
  - npm run test
  - cd client
  - npm run test